[2024-08-20T17:47:24.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-20T17:47:24.448+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.create_dataset manual__2024-08-20T17:47:07.205957+00:00 [queued]>
[2024-08-20T17:47:24.459+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.create_dataset manual__2024-08-20T17:47:07.205957+00:00 [queued]>
[2024-08-20T17:47:24.460+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-20T17:47:24.478+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): create_dataset> on 2024-08-20 17:47:07.205957+00:00
[2024-08-20T17:47:24.485+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-20T17:47:24.487+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-08-20T17:47:24.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'create_dataset', 'manual__2024-08-20T17:47:07.205957+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpkwow3pxb']
[2024-08-20T17:47:24.491+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_dataset
[2024-08-20T17:47:24.542+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline.create_dataset manual__2024-08-20T17:47:07.205957+00:00 [running]> on host 394d1672044c
[2024-08-20T17:47:24.624+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T17:47:07.205957+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T17:47:07.205957+00:00'
[2024-08-20T17:47:24.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-20T17:47:26.420+0000] {logging_mixin.py:190} INFO - Created dataset bigquery-python-433113.players in location US.
[2024-08-20T17:47:26.423+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-20T17:47:26.434+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-20T17:47:26.435+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=create_dataset, run_id=manual__2024-08-20T17:47:07.205957+00:00, execution_date=20240820T174707, start_date=20240820T174724, end_date=20240820T174726
[2024-08-20T17:47:26.480+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-20T17:47:26.509+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-20T17:47:26.514+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
